### ISSUE TITLE
Add a screenshot to readme

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/sc-starter-kit#4]
I'd like to add a screenshot of what the starter kit looks like after some content has been populated so I can display it on the `README.md`. 

All that needs done is to clone this repository down, get it setup, add some dummy products and take a screenshot of the homepage of the store.

**Comment by RageZBla** [comment]
Let me do that for you.

**Comment by RageZBla** [comment]
@damcclean I had issue with the installation process, `php artisan make:user` does not exist. On the other hand the homepage is showing some error. Any hints/advice is appreciated.

**Comment by duncanmcclean** [comment]
Ahh... sorry, you'll need to do php please make:user instead 🤦‍♂️

**Comment by duncanmcclean** [comment]
You should be able to see any errors in your log file: storage/logs

**Comment by RageZBla** [comment]
![Screen Shot 2020-10-02 at 16 18 55](https://user-images.githubusercontent.com/1196871/94897685-1c069e00-04cb-11eb-84e4-4f87add1e7e0.png)

**Comment by duncanmcclean** [comment]
Well it defiantly exists because it's this file.... https://github.com/doublethreedigital/sc-starter-kit/blob/master/resources/views/home.antlers.html

**Comment by RageZBla** [comment]
I'll check my install once more, please bear with me.
