### ISSUE TITLE
Remove Order Statuses & Product Categories

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/sc-starter-kit#60]
## Description

Just as the title says - they have been removed from Simple Commerce as it doesn't make use of them out of the box. If needed, developers can add it to the sites.

**Comment by himanshu007-creator** [comment]
hi @duncanmcclean , i would like to work on this issue. Just to be clear, issue mentions deleting these files right?
<a href="https://github.com/doublethreedigital/sc-starter-kit/blob/master/content/taxonomies/order_statuses.yaml">Order Statuses</a> and <a href="https://github.com/doublethreedigital/sc-starter-kit/blob/master/content/taxonomies/product_categories.yaml">Product Categories</a>

**Comment by duncanmcclean** [comment]
> hi @duncanmcclean , i would like to work on this issue. Just to be clear, issue mentions deleting these files right?
> [Order Statuses](https://github.com/doublethreedigital/sc-starter-kit/blob/master/content/taxonomies/order_statuses.yaml) and [Product Categories](https://github.com/doublethreedigital/sc-starter-kit/blob/master/content/taxonomies/product_categories.yaml)

Yeah, you'd need to delete those files and any other references to them inside the codebase. Thanks :)

**Comment by himanshu007-creator** [comment]
> > hi @duncanmcclean , i would like to work on this issue. Just to be clear, issue mentions deleting these files right?
> > [Order Statuses](https://github.com/doublethreedigital/sc-starter-kit/blob/master/content/taxonomies/order_statuses.yaml) and [Product Categories](https://github.com/doublethreedigital/sc-starter-kit/blob/master/content/taxonomies/product_categories.yaml)
> 
> Yeah, you'd need to delete those files and any other references to them inside the codebase. Thanks :)

can you help me locate all references in codebase?

**Comment by duncanmcclean** [comment]
You should be able to do a simple find and replace or any references of `order_statuses` or `product_categories`. Here's a few places you might find them:

* `content/taxonomies`
* `resources/blueprints/taxonomies`
* `resources/blueprints/product` - in the YAML files in there

**Comment by duncanmcclean** [comment]
Closed by #62
